insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1, 'Accepted', 'dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut', '1/8/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (3, 'Accepted', 'laoreet ut rhoncus aliquet pulvinar', '2/4/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (5, 'Accepted', 'nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac', '5/7/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (7, 'Accepted', null, null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (9, 'Accepted', 'amet nunc viverra dapibus nulla', '8/31/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (11, 'Rejected', 'quis augue luctus tincidunt nulla mollis molestie lorem quisque ut', '4/6/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (13, 'Accepted', 'porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis', '8/28/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (15, 'Accepted', 'montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem', '7/16/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (17, 'Pending', 'sodales scelerisque mauris sit amet eros suspendisse', '2/19/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (19, 'Accepted', 'blandit ultrices enim lorem ipsum', '6/3/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (21, 'Accepted', 'sociis natoque penatibus et magnis dis', '8/13/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (23, 'Accepted', 'amet diam in magna bibendum imperdiet nullam orci pede venenatis non', '4/2/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (25, 'Accepted', null, '3/17/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (27, 'Pending', 'donec semper sapien a libero nam dui proin leo', '2/14/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (29, 'Rejected', 'iaculis justo in hac habitasse platea dictumst etiam', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (31, 'Accepted', 'cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at', '5/31/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (33, 'Accepted', 'non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci', '4/20/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (35, 'Pending', 'vel nisl duis ac nibh fusce lacus', '3/11/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (37, 'Accepted', 'lacus at velit vivamus vel nulla eget eros elementum', '7/8/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (39, 'Accepted', null, '7/13/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (41, 'Rejected', 'sollicitudin vitae consectetuer eget rutrum', '8/11/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (43, 'Pending', 'in porttitor pede justo eu massa', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (45, 'Pending', 'purus sit amet nulla quisque arcu libero rutrum', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (47, 'Accepted', 'aenean fermentum donec ut mauris eget massa tempor convallis nulla', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (49, 'Pending', 'dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean', '5/22/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (51, 'Rejected', 'donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (53, 'Pending', 'pede justo lacinia eget tincidunt eget tempus', '8/2/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (55, 'Accepted', 'augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl', '10/4/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (57, 'Accepted', 'integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus', '9/4/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (59, 'Accepted', 'nulla suspendisse potenti cras in purus eu magna vulputate luctus cum', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (61, 'Pending', null, '12/14/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (63, 'Accepted', 'venenatis tristique fusce congue diam id ornare imperdiet sapien', '8/28/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (65, 'Pending', 'lacus curabitur at ipsum ac tellus semper interdum mauris', '10/28/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (67, 'Accepted', 'id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (69, 'Accepted', 'amet consectetuer adipiscing elit proin interdum mauris', '4/30/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (71, 'Accepted', 'est lacinia nisi venenatis tristique fusce congue diam id ornare', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (73, 'Pending', null, '9/19/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (75, 'Accepted', 'lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio', '2/9/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (77, 'Accepted', 'id turpis integer aliquet massa id lobortis convallis', '12/24/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (79, 'Pending', 'velit id pretium iaculis diam erat fermentum', '5/15/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (81, 'Accepted', 'maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (83, 'Accepted', null, '8/27/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (85, 'Pending', 'donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet', '1/29/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (87, 'Accepted', 'mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem', '7/17/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (89, 'Pending', 'eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec', '5/24/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (91, 'Accepted', null, '4/15/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (93, 'Accepted', 'lacus curabitur at ipsum ac tellus semper interdum mauris', '10/11/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (95, 'Accepted', 'sollicitudin mi sit amet lobortis sapien sapien', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (97, 'Pending', 'congue eget semper rutrum nulla nunc purus', '11/2/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (99, 'Accepted', 'consectetuer adipiscing elit proin risus praesent lectus vestibulum', '10/21/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (101, 'Accepted', 'nunc vestibulum ante ipsum primis in', '7/15/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (103, 'Accepted', null, '7/27/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (105, 'Pending', null, '1/2/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (107, 'Accepted', 'vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (109, 'Accepted', 'vel augue vestibulum ante ipsum primis', '2/10/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (111, 'Pending', null, null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (113, 'Accepted', 'at feugiat non pretium quis lectus suspendisse potenti in', '7/13/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (115, 'Rejected', null, '11/11/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (117, 'Accepted', 'eu felis fusce posuere felis sed lacus morbi sem mauris laoreet', '12/10/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (119, 'Accepted', null, '12/26/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (121, 'Accepted', null, '4/10/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (123, 'Accepted', null, '7/25/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (125, 'Rejected', 'nam tristique tortor eu pede', '9/22/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (127, 'Accepted', null, '3/28/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (129, 'Pending', 'ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse', '7/1/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (131, 'Accepted', 'non sodales sed tincidunt eu felis fusce posuere', '9/26/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (133, 'Accepted', 'justo in blandit ultrices enim lorem ipsum dolor', '9/28/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (135, 'Pending', 'nam congue risus semper porta volutpat quam pede', '11/1/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (137, 'Rejected', null, null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (139, 'Accepted', 'in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus', '9/14/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (141, 'Rejected', 'dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis', '9/12/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (143, 'Accepted', 'nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti', '1/22/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (145, 'Pending', null, '3/24/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (147, 'Pending', null, '6/21/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (149, 'Accepted', 'in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus', '8/21/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (151, 'Pending', 'interdum eu tincidunt in leo maecenas pulvinar lobortis', '5/12/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (153, 'Pending', 'porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla', '5/7/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (155, 'Accepted', null, '2/5/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (157, 'Pending', 'pede ac diam cras pellentesque volutpat dui maecenas tristique est et', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (159, 'Accepted', 'tortor duis mattis egestas metus', '11/20/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (161, 'Pending', 'ipsum integer a nibh in', '9/12/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (163, 'Accepted', 'porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor', '9/1/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (165, 'Accepted', 'sed accumsan felis ut at dolor quis odio consequat varius', '4/3/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (167, 'Accepted', null, null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (169, 'Accepted', null, '9/27/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (171, 'Rejected', null, '10/3/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (173, 'Accepted', 'vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia', '9/12/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (175, 'Accepted', 'in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna', '3/20/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (177, 'Pending', null, '11/25/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (179, 'Accepted', 'faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (181, 'Accepted', null, null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (183, 'Accepted', 'fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (185, 'Rejected', 'nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper', '9/25/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (187, 'Accepted', null, null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (189, 'Rejected', 'blandit non interdum in ante vestibulum ante ipsum primis in faucibus', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (191, 'Pending', 'arcu adipiscing molestie hendrerit at vulputate', '1/15/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (193, 'Pending', null, '4/13/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (195, 'Accepted', 'morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate', '6/29/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (197, 'Accepted', null, '7/29/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (199, 'Pending', 'porttitor lorem id ligula suspendisse', '6/14/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (201, 'Pending', 'rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean', '3/8/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (203, 'Pending', null, null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (205, 'Pending', null, '6/17/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (207, 'Accepted', null, '9/3/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (209, 'Accepted', 'pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea', '2/23/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (211, 'Pending', 'sit amet consectetuer adipiscing elit proin interdum mauris non', '10/15/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (213, 'Pending', 'accumsan tortor quis turpis sed ante vivamus tortor', '7/10/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (215, 'Pending', 'nulla ac enim in tempor', '3/20/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (217, 'Pending', null, '9/24/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (219, 'Accepted', 'morbi vel lectus in quam fringilla', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (221, 'Accepted', 'tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante', '6/27/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (223, 'Accepted', 'sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (225, 'Accepted', 'proin leo odio porttitor id consequat in consequat', '8/20/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (227, 'Pending', 'lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (229, 'Rejected', 'mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (231, 'Accepted', 'quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante', '4/1/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (233, 'Accepted', 'vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit', '3/18/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (235, 'Accepted', 'pede morbi porttitor lorem id ligula suspendisse ornare consequat', '5/28/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (237, 'Pending', 'rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id', '11/21/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (239, 'Accepted', 'nulla neque libero convallis eget eleifend luctus ultricies', '12/24/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (241, 'Pending', 'ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam', '7/4/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (243, 'Accepted', 'interdum eu tincidunt in leo maecenas', '5/23/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (245, 'Pending', 'in imperdiet et commodo vulputate justo in', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (247, 'Accepted', 'eu nibh quisque id justo sit amet sapien', '3/28/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (249, 'Pending', null, '4/19/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (251, 'Accepted', 'augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse', '7/2/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (253, 'Accepted', 'justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna', '11/27/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (255, 'Accepted', 'dis parturient montes nascetur ridiculus', '11/29/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (257, 'Rejected', 'lorem id ligula suspendisse ornare consequat lectus', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (259, 'Pending', 'consequat nulla nisl nunc nisl duis bibendum felis sed interdum', '12/5/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (261, 'Rejected', 'convallis nulla neque libero convallis eget', '7/15/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (263, 'Accepted', 'justo morbi ut odio cras mi', '3/13/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (265, 'Accepted', null, '6/26/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (267, 'Pending', 'in blandit ultrices enim lorem ipsum dolor sit amet consectetuer', '8/27/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (269, 'Rejected', 'at turpis donec posuere metus vitae ipsum aliquam non mauris morbi', '1/17/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (271, 'Pending', 'et ultrices posuere cubilia curae duis', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (273, 'Accepted', null, '5/8/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (275, 'Accepted', 'ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed', '3/10/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (277, 'Accepted', 'et magnis dis parturient montes nascetur ridiculus mus etiam', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (279, 'Accepted', 'vel est donec odio justo sollicitudin ut suscipit a feugiat et eros', '8/26/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (281, 'Pending', 'justo eu massa donec dapibus duis at velit eu', '9/30/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (283, 'Accepted', null, '7/26/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (285, 'Accepted', null, '2/23/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (287, 'Pending', 'curae donec pharetra magna vestibulum', '3/5/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (289, 'Accepted', null, '8/3/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (291, 'Pending', 'duis ac nibh fusce lacus purus aliquet at', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (293, 'Pending', 'curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat', '4/10/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (295, 'Accepted', 'nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac', '10/23/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (297, 'Accepted', 'magna at nunc commodo placerat praesent blandit nam nulla integer pede', '1/31/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (299, 'Accepted', 'dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (301, 'Rejected', 'vulputate vitae nisl aenean lectus', '6/9/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (303, 'Accepted', 'aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem', '8/8/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (305, 'Pending', 'purus phasellus in felis donec semper sapien a', '5/9/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (307, 'Accepted', 'posuere felis sed lacus morbi sem mauris laoreet ut rhoncus', '10/2/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (309, 'Accepted', 'justo eu massa donec dapibus duis at velit eu est congue elementum in hac', '5/23/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (311, 'Rejected', null, '12/29/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (313, 'Pending', null, null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (315, 'Pending', 'ante ipsum primis in faucibus orci luctus et', '7/18/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (317, 'Rejected', null, '2/19/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (319, 'Accepted', 'erat quisque erat eros viverra eget congue eget semper rutrum', '4/12/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (321, 'Accepted', 'mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing', '1/29/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (323, 'Pending', 'ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum', '6/10/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (325, 'Accepted', null, '1/2/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (327, 'Rejected', 'leo pellentesque ultrices mattis odio donec', '10/6/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (329, 'Accepted', 'in faucibus orci luctus et', '2/23/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (331, 'Pending', null, '7/26/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (333, 'Accepted', null, '5/16/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (335, 'Pending', 'ut suscipit a feugiat et', '9/19/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (337, 'Pending', null, '9/23/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (339, 'Accepted', 'fermentum donec ut mauris eget massa tempor convallis', '11/18/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (341, 'Pending', 'ut nulla sed accumsan felis ut', '5/3/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (343, 'Accepted', null, '6/4/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (345, 'Accepted', 'sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (347, 'Pending', 'ac leo pellentesque ultrices mattis odio donec', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (349, 'Pending', 'blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla', '4/17/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (351, 'Accepted', 'id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (353, 'Accepted', 'felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed', '4/11/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (355, 'Accepted', 'purus eu magna vulputate luctus cum', '9/21/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (357, 'Pending', 'massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (359, 'Pending', 'curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel', '7/1/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (361, 'Pending', null, null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (363, 'Pending', 'nulla sed accumsan felis ut at', '2/26/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (365, 'Accepted', 'duis faucibus accumsan odio curabitur', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (367, 'Accepted', 'dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum', '11/16/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (369, 'Rejected', 'quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent', '1/17/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (371, 'Accepted', null, null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (373, 'Rejected', 'orci eget orci vehicula condimentum curabitur', '8/9/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (375, 'Rejected', null, '4/4/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (377, 'Accepted', null, '8/3/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (379, 'Pending', 'ullamcorper purus sit amet nulla', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (381, 'Rejected', 'consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat', '8/1/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (383, 'Accepted', 'in felis eu sapien cursus vestibulum proin', '7/25/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (385, 'Accepted', 'iaculis diam erat fermentum justo nec condimentum neque', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (387, 'Pending', 'lectus vestibulum quam sapien varius ut', '9/12/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (389, 'Accepted', 'ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna', '10/23/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (391, 'Pending', 'sed vel enim sit amet nunc viverra dapibus nulla suscipit', '11/4/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (393, 'Accepted', 'non interdum in ante vestibulum ante ipsum primis in', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (395, 'Accepted', 'dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit', '2/5/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (397, 'Accepted', 'etiam faucibus cursus urna ut tellus nulla ut erat', '1/7/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (399, 'Accepted', 'non interdum in ante vestibulum ante ipsum primis in', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (401, 'Rejected', 'ut erat id mauris vulputate elementum nullam', '2/16/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (403, 'Accepted', 'vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean', '4/26/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (405, 'Accepted', 'libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (407, 'Accepted', 'nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti', '5/3/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (409, 'Accepted', 'ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut', '8/21/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (411, 'Accepted', 'quis orci eget orci vehicula condimentum curabitur in libero ut', '5/11/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (413, 'Accepted', null, '11/25/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (415, 'Pending', 'luctus cum sociis natoque penatibus et magnis', '3/23/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (417, 'Accepted', 'elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis', '2/2/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (419, 'Pending', 'pretium nisl ut volutpat sapien arcu sed augue aliquam', '9/17/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (421, 'Accepted', 'nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed', '2/13/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (423, 'Accepted', 'ac leo pellentesque ultrices mattis odio donec vitae', '2/19/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (425, 'Accepted', 'vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id', '3/14/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (427, 'Pending', 'sit amet consectetuer adipiscing elit proin interdum mauris non ligula', '3/21/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (429, 'Rejected', 'sapien arcu sed augue aliquam erat volutpat in congue etiam justo', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (431, 'Rejected', 'quam pede lobortis ligula sit amet eleifend pede libero quis orci', '6/19/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (433, 'Accepted', 'cursus id turpis integer aliquet massa', '6/24/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (435, 'Rejected', null, null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (437, 'Pending', 'aliquam erat volutpat in congue etiam justo etiam', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (439, 'Accepted', null, '5/18/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (441, 'Accepted', 'dui vel sem sed sagittis nam congue risus', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (443, 'Pending', 'in tempus sit amet sem fusce consequat', '11/14/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (445, 'Accepted', 'ante ipsum primis in faucibus orci', '11/19/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (447, 'Accepted', 'faucibus accumsan odio curabitur convallis', '11/22/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (449, 'Pending', 'odio justo sollicitudin ut suscipit a feugiat et eros vestibulum', '3/5/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (451, 'Accepted', 'ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non', '12/4/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (453, 'Accepted', null, '7/28/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (455, 'Pending', null, null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (457, 'Accepted', 'accumsan tellus nisi eu orci mauris lacinia sapien quis libero', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (459, 'Accepted', 'id massa id nisl venenatis lacinia aenean sit amet justo morbi', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (461, 'Accepted', 'interdum mauris ullamcorper purus sit amet nulla quisque', '12/1/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (463, 'Rejected', 'a suscipit nulla elit ac nulla sed vel enim', '11/26/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (465, 'Pending', 'tristique in tempus sit amet sem fusce consequat nulla', '12/8/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (467, 'Accepted', 'in magna bibendum imperdiet nullam orci', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (469, 'Pending', 'eget orci vehicula condimentum curabitur in libero', '5/4/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (471, 'Rejected', 'proin leo odio porttitor id consequat in consequat ut nulla', '10/4/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (473, 'Accepted', 'platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at', '1/8/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (475, 'Accepted', 'in tempor turpis nec euismod scelerisque quam turpis', '9/1/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (477, 'Accepted', 'ipsum primis in faucibus orci luctus', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (479, 'Accepted', 'congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (481, 'Accepted', 'tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat', '6/1/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (483, 'Accepted', 'lacus morbi quis tortor id nulla ultrices aliquet maecenas', '12/21/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (485, 'Accepted', null, '9/25/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (487, 'Pending', 'justo aliquam quis turpis eget elit sodales', '11/18/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (489, 'Rejected', 'in tempor turpis nec euismod scelerisque', '4/3/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (491, 'Pending', null, '2/25/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (493, 'Rejected', 'massa id nisl venenatis lacinia aenean sit', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (495, 'Rejected', null, '3/30/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (497, 'Accepted', 'dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec', '1/11/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (499, 'Accepted', 'congue eget semper rutrum nulla nunc', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (501, 'Pending', 'erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis', '4/26/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (503, 'Pending', 'volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim', '12/17/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (505, 'Pending', 'at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (507, 'Accepted', 'risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (509, 'Accepted', 'hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci', '6/28/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (511, 'Accepted', null, '11/30/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (513, 'Accepted', 'nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros', '5/10/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (515, 'Accepted', 'odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar', '10/9/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (517, 'Rejected', null, '1/14/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (519, 'Rejected', 'curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (521, 'Pending', null, '3/14/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (523, 'Pending', 'eros vestibulum ac est lacinia nisi venenatis tristique fusce congue', '1/12/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (525, 'Pending', 'in consequat ut nulla sed accumsan', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (527, 'Pending', 'massa tempor convallis nulla neque libero convallis eget eleifend', '9/3/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (529, 'Accepted', null, '12/22/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (531, 'Pending', null, null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (533, 'Pending', 'ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus', '6/28/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (535, 'Accepted', 'consequat lectus in est risus auctor sed tristique in', '7/29/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (537, 'Accepted', 'cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (539, 'Pending', 'nisi vulputate nonummy maecenas tincidunt lacus at', '7/14/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (541, 'Pending', 'morbi a ipsum integer a nibh in quis', '8/19/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (543, 'Accepted', 'nulla sed accumsan felis ut at dolor quis odio consequat varius', '4/10/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (545, 'Pending', 'primis in faucibus orci luctus', '12/3/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (547, 'Accepted', 'eget elit sodales scelerisque mauris sit amet', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (549, 'Accepted', 'aliquet pulvinar sed nisl nunc rhoncus dui vel', '5/19/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (551, 'Pending', 'amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque', '3/23/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (553, 'Accepted', 'vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor', '5/2/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (555, 'Accepted', 'lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in', '10/15/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (557, 'Accepted', 'faucibus orci luctus et ultrices posuere', '5/3/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (559, 'Rejected', 'diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (561, 'Accepted', null, '10/31/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (563, 'Accepted', 'sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue', '9/21/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (565, 'Accepted', 'aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo', '10/29/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (567, 'Accepted', 'fusce congue diam id ornare imperdiet sapien urna', '8/4/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (569, 'Pending', 'luctus nec molestie sed justo pellentesque viverra', '12/30/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (571, 'Accepted', 'pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat', '2/8/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (573, 'Accepted', null, '6/13/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (575, 'Accepted', null, null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (577, 'Rejected', 'sed accumsan felis ut at dolor quis odio consequat varius integer ac leo', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (579, 'Accepted', null, '12/8/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (581, 'Accepted', 'mauris non ligula pellentesque ultrices phasellus', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (583, 'Accepted', 'hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget', '8/15/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (585, 'Accepted', 'congue risus semper porta volutpat quam', '9/12/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (587, 'Pending', 'eget rutrum at lorem integer tincidunt ante', '12/9/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (589, 'Accepted', null, null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (591, 'Accepted', 'pede venenatis non sodales sed tincidunt eu', '7/29/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (593, 'Accepted', 'vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae', '10/2/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (595, 'Pending', 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (597, 'Pending', 'luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam', '3/20/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (599, 'Accepted', 'consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (601, 'Pending', null, '6/29/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (603, 'Rejected', null, '3/1/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (605, 'Accepted', 'vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (607, 'Accepted', null, '9/5/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (609, 'Accepted', 'habitasse platea dictumst morbi vestibulum velit id', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (611, 'Accepted', 'platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt', '12/26/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (613, 'Accepted', null, '12/1/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (615, 'Accepted', null, '11/4/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (617, 'Pending', 'sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (619, 'Accepted', 'blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum', '9/5/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (621, 'Pending', 'platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (623, 'Accepted', 'sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit', '4/2/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (625, 'Pending', 'ligula sit amet eleifend pede libero quis orci', '5/21/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (627, 'Pending', 'sem fusce consequat nulla nisl nunc nisl duis bibendum felis', '12/1/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (629, 'Accepted', 'vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum', '12/7/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (631, 'Accepted', 'morbi odio odio elementum eu interdum eu tincidunt in leo', '2/21/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (633, 'Accepted', 'non interdum in ante vestibulum ante ipsum primis in faucibus orci', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (635, 'Accepted', 'non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac', '11/25/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (637, 'Pending', 'pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique', '12/19/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (639, 'Accepted', 'tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh', '3/19/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (641, 'Pending', 'nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed', '3/21/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (643, 'Pending', 'duis aliquam convallis nunc proin at turpis a pede posuere nonummy', '2/6/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (645, 'Pending', 'nulla sed accumsan felis ut at dolor', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (647, 'Accepted', null, null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (649, 'Pending', null, '1/30/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (651, 'Pending', 'metus aenean fermentum donec ut mauris eget', '4/2/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (653, 'Pending', null, '2/12/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (655, 'Pending', 'in consequat ut nulla sed accumsan', '6/26/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (657, 'Accepted', 'lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus', '9/4/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (659, 'Accepted', 'venenatis turpis enim blandit mi in porttitor pede justo', '3/29/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (661, 'Rejected', 'vel sem sed sagittis nam', '6/16/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (663, 'Rejected', null, '5/17/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (665, 'Pending', 'nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum', '8/28/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (667, 'Accepted', 'sociis natoque penatibus et magnis dis parturient', '9/12/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (669, 'Accepted', 'vestibulum ante ipsum primis in', '3/21/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (671, 'Pending', null, '11/1/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (673, 'Pending', null, '8/27/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (675, 'Accepted', 'pede ullamcorper augue a suscipit nulla', '12/21/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (677, 'Rejected', 'tortor risus dapibus augue vel', '9/9/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (679, 'Accepted', 'enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin', '8/21/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (681, 'Pending', 'quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo', '7/24/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (683, 'Accepted', 'tincidunt lacus at velit vivamus vel nulla eget eros elementum', '3/30/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (685, 'Accepted', 'justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis', '3/30/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (687, 'Rejected', 'scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec', '10/3/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (689, 'Accepted', 'praesent blandit nam nulla integer pede justo lacinia eget', '1/12/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (691, 'Accepted', 'odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla', '5/27/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (693, 'Pending', 'purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient', '11/24/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (695, 'Accepted', 'aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit', '6/22/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (697, 'Pending', 'ipsum primis in faucibus orci luctus et ultrices posuere', '12/28/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (699, 'Accepted', 'natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum', '9/6/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (701, 'Pending', 'amet lobortis sapien sapien non mi integer ac neque duis bibendum', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (703, 'Pending', 'suspendisse potenti in eleifend quam a', '7/10/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (705, 'Pending', 'curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (707, 'Accepted', 'tempor convallis nulla neque libero convallis eget eleifend', '4/1/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (709, 'Pending', null, null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (711, 'Accepted', 'congue vivamus metus arcu adipiscing molestie hendrerit at', '4/3/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (713, 'Accepted', null, '4/9/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (715, 'Pending', 'leo maecenas pulvinar lobortis est phasellus sit amet erat', '12/17/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (717, 'Rejected', 'quis orci eget orci vehicula condimentum', '3/10/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (719, 'Accepted', null, '9/30/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (721, 'Pending', 'semper est quam pharetra magna ac consequat', '11/19/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (723, 'Accepted', 'felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar', '9/28/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (725, 'Accepted', 'amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (727, 'Pending', 'interdum in ante vestibulum ante ipsum primis in faucibus', '2/18/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (729, 'Pending', 'pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus', '8/31/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (731, 'Accepted', 'justo lacinia eget tincidunt eget tempus vel pede morbi porttitor', '6/9/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (733, 'Accepted', 'cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim', '2/6/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (735, 'Accepted', 'nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate', '2/10/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (737, 'Pending', null, '10/29/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (739, 'Pending', 'proin leo odio porttitor id consequat', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (741, 'Pending', 'eu orci mauris lacinia sapien quis libero nullam sit', '10/9/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (743, 'Accepted', 'tellus nisi eu orci mauris lacinia sapien quis libero nullam', '4/5/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (745, 'Accepted', 'porttitor pede justo eu massa donec dapibus duis at velit', '10/26/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (747, 'Pending', null, null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (749, 'Accepted', null, '5/9/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (751, 'Accepted', 'vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare', '12/9/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (753, 'Pending', 'et tempus semper est quam pharetra magna ac', '4/9/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (755, 'Accepted', null, '8/1/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (757, 'Pending', 'pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (759, 'Accepted', 'elementum nullam varius nulla facilisi cras', '3/17/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (761, 'Pending', 'mauris ullamcorper purus sit amet nulla quisque arcu', '12/30/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (763, 'Pending', 'tempus vel pede morbi porttitor', '9/2/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (765, 'Pending', 'bibendum morbi non quam nec dui luctus rutrum nulla tellus in', '4/23/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (767, 'Pending', 'eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget', '12/28/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (769, 'Pending', 'auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc', '12/1/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (771, 'Accepted', 'arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium', '9/17/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (773, 'Pending', 'quis lectus suspendisse potenti in eleifend quam a odio', '7/17/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (775, 'Pending', 'non interdum in ante vestibulum ante', '7/23/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (777, 'Pending', 'purus phasellus in felis donec semper sapien a libero nam', '6/2/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (779, 'Pending', 'consequat ut nulla sed accumsan', '3/1/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (781, 'Pending', 'orci nullam molestie nibh in lectus', '9/26/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (783, 'Pending', 'donec ut dolor morbi vel lectus', '1/16/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (785, 'Rejected', 'id sapien in sapien iaculis', '11/10/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (787, 'Pending', 'fusce congue diam id ornare imperdiet sapien', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (789, 'Accepted', 'congue eget semper rutrum nulla nunc purus', '4/19/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (791, 'Pending', 'at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum', '2/29/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (793, 'Rejected', 'ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', '2/19/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (795, 'Accepted', 'nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi', '1/22/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (797, 'Pending', 'luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam', '5/7/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (799, 'Pending', 'vestibulum sit amet cursus id turpis', '2/13/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (801, 'Accepted', 'sapien sapien non mi integer', '3/18/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (803, 'Pending', 'sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet', '9/4/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (805, 'Pending', 'non sodales sed tincidunt eu felis fusce', '8/3/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (807, 'Accepted', 'odio consequat varius integer ac leo pellentesque ultrices mattis', '11/13/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (809, 'Accepted', 'sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl', '2/8/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (811, 'Pending', 'pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non', '1/15/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (813, 'Pending', 'risus dapibus augue vel accumsan tellus nisi eu', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (815, 'Pending', 'nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam', '10/19/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (817, 'Accepted', 'accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (819, 'Accepted', null, '3/31/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (821, 'Accepted', 'rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin', '12/18/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (823, 'Accepted', null, null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (825, 'Accepted', 'fusce consequat nulla nisl nunc nisl', '6/2/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (827, 'Pending', 'tempor convallis nulla neque libero convallis eget eleifend', '10/23/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (829, 'Rejected', 'lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id', '1/30/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (831, 'Accepted', null, '8/25/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (833, 'Pending', null, '11/3/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (835, 'Accepted', 'donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam', '2/10/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (837, 'Pending', null, null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (839, 'Pending', 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor', '6/8/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (841, 'Rejected', 'curabitur at ipsum ac tellus semper interdum mauris ullamcorper', '2/23/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (843, 'Accepted', 'platea dictumst maecenas ut massa quis augue', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (845, 'Pending', 'cursus id turpis integer aliquet massa id lobortis convallis', '4/11/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (847, 'Accepted', 'sapien arcu sed augue aliquam erat volutpat in congue etiam', '3/15/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (849, 'Pending', 'mauris laoreet ut rhoncus aliquet', '10/28/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (851, 'Pending', 'nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque', '11/8/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (853, 'Pending', 'in libero ut massa volutpat', '11/8/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (855, 'Accepted', 'curae donec pharetra magna vestibulum aliquet ultrices erat', '12/4/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (857, 'Accepted', 'bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede', '8/19/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (859, 'Accepted', 'eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus', '4/11/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (861, 'Accepted', 'in hac habitasse platea dictumst etiam faucibus cursus urna', '5/6/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (863, 'Pending', 'varius nulla facilisi cras non velit nec nisi', '5/14/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (865, 'Pending', null, null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (867, 'Accepted', 'varius ut blandit non interdum in', '6/22/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (869, 'Pending', null, '6/7/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (871, 'Pending', 'cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at', '7/15/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (873, 'Pending', 'arcu sed augue aliquam erat', '10/12/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (875, 'Pending', 'pellentesque ultrices phasellus id sapien in sapien', '10/7/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (877, 'Accepted', 'semper sapien a libero nam', '6/27/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (879, 'Rejected', 'quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (881, 'Pending', 'primis in faucibus orci luctus et ultrices posuere', '5/4/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (883, 'Pending', 'vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt', '4/20/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (885, 'Pending', 'in sagittis dui vel nisl duis ac nibh', '7/30/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (887, 'Pending', 'venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat', '6/6/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (889, 'Accepted', 'lacinia sapien quis libero nullam', '1/19/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (891, 'Pending', 'rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis', '3/12/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (893, 'Pending', 'neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis', '2/26/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (895, 'Pending', 'felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa', '3/29/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (897, 'Rejected', 'in felis eu sapien cursus vestibulum', '10/19/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (899, 'Accepted', 'donec pharetra magna vestibulum aliquet ultrices erat tortor', '2/17/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (901, 'Pending', 'in ante vestibulum ante ipsum primis in', '4/12/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (903, 'Pending', 'maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet', '1/10/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (905, 'Accepted', null, '11/22/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (907, 'Accepted', 'integer pede justo lacinia eget tincidunt eget', '11/17/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (909, 'Pending', 'mauris viverra diam vitae quam suspendisse potenti nullam', '3/21/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (911, 'Pending', 'nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing', '7/27/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (913, 'Rejected', 'dolor sit amet consectetuer adipiscing elit proin risus praesent', '11/7/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (915, 'Accepted', 'in tempus sit amet sem fusce consequat nulla', '11/7/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (917, 'Pending', null, '9/19/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (919, 'Rejected', null, '5/10/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (921, 'Rejected', 'diam in magna bibendum imperdiet', '2/15/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (923, 'Rejected', 'sapien cursus vestibulum proin eu mi nulla ac enim', '4/16/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (925, 'Pending', 'risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in', '6/24/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (927, 'Pending', 'odio elementum eu interdum eu tincidunt in leo maecenas', '6/4/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (929, 'Pending', 'nullam orci pede venenatis non sodales sed tincidunt', '10/25/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (931, 'Pending', 'ipsum dolor sit amet consectetuer adipiscing', '3/17/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (933, 'Accepted', 'eget orci vehicula condimentum curabitur in libero', '12/25/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (935, 'Pending', 'adipiscing elit proin risus praesent lectus vestibulum quam sapien', '1/11/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (937, 'Accepted', 'ipsum dolor sit amet consectetuer adipiscing elit proin risus praesent lectus', '4/30/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (939, 'Pending', 'in magna bibendum imperdiet nullam orci pede venenatis non', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (941, 'Rejected', 'diam in magna bibendum imperdiet', '6/18/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (943, 'Accepted', null, null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (945, 'Pending', 'ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (947, 'Accepted', 'in purus eu magna vulputate luctus cum sociis', '2/5/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (949, 'Accepted', 'nunc nisl duis bibendum felis sed interdum venenatis turpis enim', '8/12/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (951, 'Pending', 'at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat', '5/3/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (953, 'Pending', 'primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio', '4/9/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (955, 'Rejected', 'orci eget orci vehicula condimentum curabitur in libero ut', '2/21/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (957, 'Pending', 'nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus', '1/4/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (959, 'Pending', 'tempus sit amet sem fusce consequat nulla nisl nunc nisl duis', '1/27/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (961, 'Pending', 'nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit', '4/5/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (963, 'Accepted', null, '3/28/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (965, 'Pending', 'in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus', '9/10/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (967, 'Pending', 'bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (969, 'Accepted', 'potenti in eleifend quam a odio in', '1/11/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (971, 'Accepted', null, '3/31/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (973, 'Pending', null, '12/18/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (975, 'Pending', null, '4/9/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (977, 'Accepted', 'diam vitae quam suspendisse potenti', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (979, 'Rejected', null, '10/3/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (981, 'Accepted', 'sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis', '12/4/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (983, 'Pending', 'viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper', '8/25/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (985, 'Accepted', 'in faucibus orci luctus et ultrices posuere cubilia curae', '8/29/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (987, 'Accepted', null, '10/4/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (989, 'Accepted', 'hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer', '7/9/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (991, 'Accepted', null, '11/9/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (993, 'Accepted', null, '10/18/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (995, 'Pending', 'lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (997, 'Accepted', 'congue eget semper rutrum nulla nunc purus phasellus in felis', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (999, 'Pending', 'id pretium iaculis diam erat fermentum justo nec condimentum neque sapien', '3/18/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1001, 'Accepted', 'vestibulum proin eu mi nulla ac enim', '10/1/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1003, 'Pending', 'amet eros suspendisse accumsan tortor quis turpis sed', '10/4/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1005, 'Rejected', 'lectus pellentesque eget nunc donec', '8/19/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1007, 'Accepted', 'dictumst aliquam augue quam sollicitudin', '7/8/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1009, 'Pending', 'orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed', '3/8/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1011, 'Accepted', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec', '7/4/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1013, 'Accepted', null, null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1015, 'Pending', 'hac habitasse platea dictumst etiam faucibus cursus', '6/18/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1017, 'Pending', 'tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean', '9/22/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1019, 'Pending', 'gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer', '12/25/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1021, 'Accepted', 'augue luctus tincidunt nulla mollis molestie', '9/26/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1023, 'Accepted', 'erat vestibulum sed magna at nunc', '9/24/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1025, 'Accepted', 'molestie lorem quisque ut erat curabitur', '11/10/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1027, 'Accepted', 'in consequat ut nulla sed', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1029, 'Pending', 'augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1031, 'Accepted', null, '8/16/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1033, 'Pending', 'eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas', '12/13/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1035, 'Accepted', 'orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti', '7/11/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1037, 'Accepted', 'ligula vehicula consequat morbi a ipsum integer a', '11/30/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1039, 'Accepted', 'luctus et ultrices posuere cubilia curae donec', '7/22/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1041, 'Accepted', 'amet justo morbi ut odio cras mi pede malesuada in imperdiet', '6/29/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1043, 'Rejected', 'feugiat non pretium quis lectus', '1/1/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1045, 'Pending', 'in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at', '12/29/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1047, 'Rejected', 'non velit donec diam neque vestibulum eget vulputate ut', '5/18/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1049, 'Accepted', 'semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam', '5/27/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1051, 'Rejected', 'diam cras pellentesque volutpat dui maecenas tristique est', '10/19/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1053, 'Accepted', 'lectus vestibulum quam sapien varius ut blandit non interdum', '2/24/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1055, 'Pending', null, '2/19/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1057, 'Pending', 'dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1059, 'Pending', 'id massa id nisl venenatis lacinia aenean sit amet justo', '4/21/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1061, 'Accepted', 'massa quis augue luctus tincidunt', '5/6/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1063, 'Accepted', 'nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue', '6/18/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1065, 'Accepted', 'amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque', '4/29/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1067, 'Pending', 'sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus', '6/20/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1069, 'Accepted', 'non velit nec nisi vulputate nonummy', '12/5/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1071, 'Rejected', 'nulla sed accumsan felis ut at', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1073, 'Accepted', null, null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1075, 'Accepted', 'auctor gravida sem praesent id', '10/4/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1077, 'Rejected', 'integer ac neque duis bibendum morbi non quam nec', '3/23/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1079, 'Pending', null, '9/21/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1081, 'Pending', 'donec semper sapien a libero nam', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1083, 'Accepted', 'ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla', '3/22/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1085, 'Accepted', 'ultrices vel augue vestibulum ante ipsum primis', '11/18/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1087, 'Accepted', 'metus vitae ipsum aliquam non', '10/24/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1089, 'Pending', 'lorem quisque ut erat curabitur gravida nisi at nibh', '5/27/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1091, 'Pending', 'convallis nunc proin at turpis a pede posuere nonummy', '2/27/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1093, 'Accepted', null, '11/28/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1095, 'Rejected', 'cubilia curae duis faucibus accumsan odio', '2/7/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1097, 'Pending', 'natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum', '2/28/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1099, 'Pending', null, '8/4/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1101, 'Pending', 'faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum', '10/8/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1103, 'Accepted', 'nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique', '8/27/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1105, 'Accepted', 'penatibus et magnis dis parturient montes', '9/24/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1107, 'Rejected', 'vestibulum rutrum rutrum neque aenean auctor gravida sem praesent', '9/1/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1109, 'Pending', 'orci pede venenatis non sodales sed tincidunt eu felis fusce posuere', '10/7/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1111, 'Accepted', 'proin eu mi nulla ac enim in tempor turpis nec', '1/8/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1113, 'Accepted', 'ut nulla sed accumsan felis ut at dolor', '10/7/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1115, 'Rejected', 'lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede', '9/20/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1117, 'Pending', null, '9/26/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1119, 'Accepted', 'quisque ut erat curabitur gravida nisi', '1/26/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1121, 'Accepted', null, '6/23/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1123, 'Accepted', 'lectus vestibulum quam sapien varius ut blandit non interdum', '6/19/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1125, 'Pending', 'ultrices libero non mattis pulvinar nulla pede', '2/22/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1127, 'Accepted', 'dui vel sem sed sagittis nam congue risus', '7/15/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1129, 'Pending', 'habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat', '10/29/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1131, 'Rejected', 'pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo', '9/17/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1133, 'Pending', null, null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1135, 'Rejected', 'felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl', '5/23/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1137, 'Pending', null, null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1139, 'Pending', 'platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec', '4/28/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1141, 'Pending', null, '2/19/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1143, 'Accepted', 'sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi', '10/17/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1145, 'Pending', null, '7/21/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1147, 'Accepted', 'odio cras mi pede malesuada in imperdiet et commodo vulputate', '11/8/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1149, 'Rejected', null, '2/21/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1151, 'Accepted', null, '5/30/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1153, 'Pending', 'pulvinar nulla pede ullamcorper augue a suscipit nulla elit', '3/31/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1155, 'Accepted', 'diam cras pellentesque volutpat dui maecenas tristique est', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1157, 'Pending', 'auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl', '6/4/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1159, 'Rejected', 'integer non velit donec diam neque vestibulum', '12/3/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1161, 'Pending', 'commodo vulputate justo in blandit ultrices', '3/8/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1163, 'Accepted', 'sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat', '6/14/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1165, 'Pending', 'primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam', '5/3/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1167, 'Rejected', 'interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus', '5/22/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1169, 'Pending', 'consequat lectus in est risus auctor sed tristique in', '11/13/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1171, 'Pending', null, '12/1/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1173, 'Pending', 'sagittis dui vel nisl duis ac', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1175, 'Accepted', 'vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus', '6/27/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1177, 'Pending', null, '1/23/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1179, 'Pending', 'vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim', '11/11/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1181, 'Accepted', null, null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1183, 'Pending', 'quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi', '6/1/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1185, 'Pending', 'morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus', '2/4/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1187, 'Accepted', 'est quam pharetra magna ac consequat metus sapien ut', '2/21/2024');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1189, 'Pending', 'libero rutrum ac lobortis vel dapibus at diam nam tristique', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1191, 'Pending', 'vestibulum ante ipsum primis in faucibus orci luctus et', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1193, 'Pending', 'orci eget orci vehicula condimentum curabitur in libero ut', null);
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1195, 'Accepted', 'quis tortor id nulla ultrices aliquet maecenas leo', '6/14/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1197, 'Pending', 'bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce', '10/4/2023');
insert into AdStatus (AdvertisementID, AdState, AdminComment, UpdatedAt) values (1199, 'Rejected', 'aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum', '1/21/2024');
