insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (609, 4, 80, 'Not Good', 'amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (391, 2, 100, null, 'gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (417, 2, 64, 'Offensive', null);
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (941, 7, 98, 'Offensive', 'in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (353, 9, 108, 'Not Good', 'lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (53, 8, 84, 'WTF is this', null);
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (157, 1, 28, null, 'dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (645, 10, 52, 'Offensive', 'pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (717, 10, 72, 'Bad Word', 'volutpat erat quisque erat eros viverra eget congue eget semper');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (717, 11, 72, 'Bad Word', 'volutpat erat quisque erat eros viverra eget congue eget semper');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (19, 4, 52, 'Not Good', 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (433, 8, 4, 'Offensive', 'blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (937, 9, 46, 'Not Accurate', 'phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (129, 6, 56, 'Offensive', 'sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (359, 3, 48, 'Not Good', 'nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (853, 10, 22, null, 'amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (723, 10, 62, 'WTF is this', null);
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (589, 6, 102, 'WTF is this', 'tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (633, 9, 42, 'Offensive', 'ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (545, 6, 86, 'WTF is this', 'convallis nunc proin at turpis a pede posuere nonummy integer');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (509, 9, 106, 'Offensive', 'turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (953, 5, 72, 'Not Accurate', 'sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (105, 2, 60, 'Offensive', null);
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (953, 4, 60, 'Not Accurate', 'sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (151, 10, 44, 'Not Good', 'metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (717, 3, 74, 'WTF is this', 'turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (647, 5, 90, 'Not Accurate', null);
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (67, 2, 40, 'Offensive', 'non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (725, 6, 110, 'Offensive', null);
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (107, 3, 4, 'Not Accurate', 'ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (717, 2, 12, 'Offensive', 'amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (695, 1, 116, 'Bad Word', null);
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (629, 6, 16, 'WTF is this', 'duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (681, 7, 74, 'Bad Word', 'duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (813, 6, 64, 'Not Good', null);
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (589, 5, 18, 'Bad Word', null);
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (569, 3, 106, null, 'elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (119, 8, 108, 'Not Accurate', 'hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (7, 3, 24, 'Not Accurate', 'non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (833, 7, 112, 'Bad Word', 'morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (429, 1, 58, 'Not Accurate', 'tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (819, 4, 70, 'WTF is this', 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (977, 1, 68, 'WTF is this', null);
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (555, 10, 30, 'Not Accurate', 'ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (83, 9, 86, 'WTF is this', null);
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (285, 3, 72, 'WTF is this', 'justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (903, 4, 20, 'WTF is this', 'ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (489, 4, 4, 'Bad Word', 'libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (875, 6, 4, 'WTF is this', 'donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (231, 10, 106, null, 'vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (875, 9, 54, 'Offensive', 'morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum');
insert into Report (AdvertisementID, ReportID, UserID, Category, RDesc) values (605, 3, 116, 'Not Accurate', 'nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel');
